#!/usr/bin/env python3
"""
Analytics Git Integration
Automatically commits analytics reports to GitHub with structured messaging
"""

import subprocess
import json
from pathlib import Path
from datetime import datetime
import logging

logger = logging.getLogger("AnalyticsGitIntegration")
handler = logging.FileHandler(Path("logs") / "analytics_git.log")
handler.setFormatter(logging.Formatter('[%(asctime)s] %(levelname)s - %(message)s'))
logger.addHandler(handler)
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.INFO)


class AnalyticsGitIntegration:
    """Handles Git commits for analytics reports"""

    def __init__(self, repo_path: str = "."):
        self.repo_path = Path(repo_path)
        self.reports_dir = self.repo_path / "reports"

    def commit_analytics_report(self, report_path: Path, milestone: str = None) -> bool:
        """
        Commit analytics report to Git with structured messaging

        Args:
            report_path: Path to the report file
            milestone: Optional milestone name (e.g., "phase_1_complete", "post_handshake")

        Returns:
            True if commit successful, False otherwise
        """
        try:
            # Check if report exists
            if not report_path.exists():
                logger.error(f"Report file not found: {report_path}")
                return False

            # Stage the file
            result = subprocess.run(
                ["git", "add", str(report_path)],
                cwd=str(self.repo_path),
                capture_output=True,
                text=True
            )

            if result.returncode != 0:
                logger.error(f"Failed to stage file: {result.stderr}")
                return False

            # Generate commit message
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            milestone_tag = f"[{milestone}] " if milestone else ""

            commit_message = f"""
{milestone_tag}Analytics Report - {timestamp}

## Report Summary
- Report: {report_path.name}
- Generated: {timestamp}
- Repository: Analytics & Collaboration Data

## Key Metrics Captured
- Message communication patterns
- Agent collaboration quality
- Phase progression tracking
- Decision points and blockers
- Keyword frequency analysis
- Sentiment distribution

## Purpose
This analytics report captures the evolution of Claude-Gemini collaboration
and supports:
1. System optimization insights
2. Emergent property detection
3. Collaboration quality tracking
4. ML training data for agent communication
5. Project phase milestone documentation

## Next Review
Check the reports directory for JSON (machine-readable) and
Markdown (human-readable) versions.

---
Generated by: conversation_analytics_engine.py
Integration: analytics_git_integration.py
"""

            # Commit with structured message
            result = subprocess.run(
                ["git", "commit", "-m", commit_message.strip()],
                cwd=str(self.repo_path),
                capture_output=True,
                text=True
            )

            if result.returncode == 0:
                logger.info(f"Successfully committed: {report_path.name}")
                logger.info(f"Commit message: {commit_message[:100]}...")
                return True
            else:
                logger.warning(f"Git commit returned code {result.returncode}: {result.stderr}")
                # This could be because there are no changes, which is OK
                if "nothing to commit" in result.stderr.lower():
                    logger.info("No changes to commit (report already committed)")
                    return True
                return False

        except Exception as e:
            logger.error(f"Exception during commit: {e}")
            return False

    def push_to_remote(self, remote: str = "origin", branch: str = "main") -> bool:
        """Push committed analytics to remote repository"""
        try:
            result = subprocess.run(
                ["git", "push", remote, branch],
                cwd=str(self.repo_path),
                capture_output=True,
                text=True
            )

            if result.returncode == 0:
                logger.info(f"Successfully pushed to {remote}/{branch}")
                return True
            else:
                logger.warning(f"Push failed: {result.stderr}")
                return False

        except Exception as e:
            logger.error(f"Exception during push: {e}")
            return False

    def commit_with_milestone(self, report_path: Path, milestone: str) -> bool:
        """Commit with milestone tag"""
        return self.commit_analytics_report(report_path, milestone)

    def auto_commit_daily(self) -> bool:
        """Auto-commit latest analytics report daily"""
        # Find most recent report
        if not self.reports_dir.exists():
            logger.warning("Reports directory does not exist")
            return False

        reports = sorted(self.reports_dir.glob("analytics_report_*.json"), reverse=True)
        if not reports:
            logger.warning("No analytics reports found")
            return False

        latest_report = reports[0]
        logger.info(f"Auto-committing latest report: {latest_report.name}")

        return self.commit_analytics_report(latest_report, milestone="daily_analytics")


def main():
    """Example usage"""
    integration = AnalyticsGitIntegration()

    # Example: commit a report with milestone
    # integration.commit_with_milestone(
    #     Path("reports/analytics_report_20251125_020000.json"),
    #     "phase_1_complete"
    # )

    # Example: auto-commit latest
    success = integration.auto_commit_daily()

    if success:
        print("Analytics report committed to Git successfully")
    else:
        print("Failed to commit analytics report")


if __name__ == "__main__":
    main()
